### ISSUE TITLE
Hip Hop and Metal channel missing in FIP

### ISSUE THREAD

**Issue by stiefenm** [PaulWebster/RadioFrance#4]
Seems that FIP has added new channels recently: Hip Hop and Metal:
https://www.radiofrance.fr/fip/radio-hip-hop
https://www.radiofrance.fr/fip/radio-metal

I'd love to be able to access them via the Radio France LMS plugin. Would it be possible to add them?

Best regards and thank you for this project which made it possible to listen to my favourite station for years.

Marek

**Comment by PaulWebster** [comment]
Beta now available (0.4.3b) with these two. Send me an email via the Slimdevices forum if you do not have the URL to get the beta.
You might find that Metal works without an update because this used to exist long ago and the underlying data appears to be the same (you will have to find the stream URL via something else until you have this beta).

**Comment by PaulWebster** [comment]
0.4.3 released
https://github.com/PaulWebster/RadioFrance/commit/3fb8d74675e4164a78db3cbefad6735fcf94457e
